const WORLD_CUP_SOURCE =
  "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/match-schedule-fixtures-results-teams-stadiums";

const GROUPS = {
  A: ["México", "Sudáfrica", "Corea del Sur", "Chequia"],
  B: ["Canadá", "Bosnia y Herzegovina", "Qatar", "Suiza"],
  C: ["Brasil", "Marruecos", "Haití", "Escocia"],
  D: ["Estados Unidos", "Paraguay", "Australia", "Turquía"],
  E: ["Alemania", "Curazao", "Costa de Marfil", "Ecuador"],
  F: ["Países Bajos", "Japón", "Túnez", "Suecia"],
  G: ["Bélgica", "Egipto", "Irán", "Nueva Zelanda"],
  H: ["España", "Cabo Verde", "Arabia Saudí", "Uruguay"],
  I: ["Francia", "Senegal", "Noruega", "Irak"],
  J: ["Argentina", "Argelia", "Austria", "Jordania"],
  K: ["Portugal", "Uzbekistán", "Colombia", "RD Congo"],
  L: ["Inglaterra", "Croacia", "Ghana", "Panamá"],
};

const FLAG_CODES = {
  "Alemania": "de",
  "Arabia Saudí": "sa",
  "Argelia": "dz",
  "Argentina": "ar",
  "Australia": "au",
  "Austria": "at",
  "Bélgica": "be",
  "Bosnia y Herzegovina": "ba",
  "Brasil": "br",
  "Cabo Verde": "cv",
  "Canadá": "ca",
  "Chequia": "cz",
  "Colombia": "co",
  "Corea del Sur": "kr",
  "Costa de Marfil": "ci",
  "Croacia": "hr",
  "Curazao": "cw",
  "Ecuador": "ec",
  "Egipto": "eg",
  "Escocia": "gb-sct",
  "España": "es",
  "Estados Unidos": "us",
  "Francia": "fr",
  "Ghana": "gh",
  "Haití": "ht",
  "Inglaterra": "gb-eng",
  "Irak": "iq",
  "Irán": "ir",
  "Japón": "jp",
  "Jordania": "jo",
  "Marruecos": "ma",
  "México": "mx",
  "Noruega": "no",
  "Nueva Zelanda": "nz",
  "Países Bajos": "nl",
  "Panamá": "pa",
  "Paraguay": "py",
  "Portugal": "pt",
  "Qatar": "qa",
  "RD Congo": "cd",
  "Senegal": "sn",
  "Sudáfrica": "za",
  "Suecia": "se",
  "Suiza": "ch",
  "Túnez": "tn",
  "Turquía": "tr",
  "Uruguay": "uy",
  "Uzbekistán": "uz",
};

const MATCHES = [
  ["2026-06-11", "A", "México", "Sudáfrica", "Mexico City Stadium"],
  ["2026-06-11", "A", "Corea del Sur", "Chequia", "Estadio Guadalajara"],
  ["2026-06-12", "B", "Canadá", "Bosnia y Herzegovina", "Toronto Stadium"],
  ["2026-06-12", "D", "Estados Unidos", "Paraguay", "Los Angeles Stadium"],
  ["2026-06-13", "C", "Haití", "Escocia", "Boston Stadium"],
  ["2026-06-13", "D", "Australia", "Turquía", "BC Place Vancouver"],
  ["2026-06-13", "C", "Brasil", "Marruecos", "New York New Jersey Stadium"],
  ["2026-06-13", "B", "Qatar", "Suiza", "San Francisco Bay Area Stadium"],
  ["2026-06-14", "E", "Costa de Marfil", "Ecuador", "Philadelphia Stadium"],
  ["2026-06-14", "E", "Alemania", "Curazao", "Houston Stadium"],
  ["2026-06-14", "F", "Países Bajos", "Japón", "Dallas Stadium"],
  ["2026-06-14", "F", "Suecia", "Túnez", "Estadio Monterrey"],
  ["2026-06-15", "H", "Arabia Saudí", "Uruguay", "Miami Stadium"],
  ["2026-06-15", "H", "España", "Cabo Verde", "Atlanta Stadium"],
  ["2026-06-15", "G", "Irán", "Nueva Zelanda", "Los Angeles Stadium"],
  ["2026-06-15", "G", "Bélgica", "Egipto", "Seattle Stadium"],
  ["2026-06-16", "I", "Francia", "Senegal", "New York New Jersey Stadium"],
  ["2026-06-16", "I", "Irak", "Noruega", "Boston Stadium"],
  ["2026-06-16", "J", "Argentina", "Argelia", "Kansas City Stadium"],
  ["2026-06-16", "J", "Austria", "Jordania", "San Francisco Bay Area Stadium"],
  ["2026-06-17", "L", "Ghana", "Panamá", "Toronto Stadium"],
  ["2026-06-17", "L", "Inglaterra", "Croacia", "Dallas Stadium"],
  ["2026-06-17", "K", "Portugal", "RD Congo", "Houston Stadium"],
  ["2026-06-17", "K", "Uzbekistán", "Colombia", "Mexico City Stadium"],
  ["2026-06-18", "A", "Chequia", "Sudáfrica", "Atlanta Stadium"],
  ["2026-06-18", "B", "Suiza", "Bosnia y Herzegovina", "Los Angeles Stadium"],
  ["2026-06-18", "B", "Canadá", "Qatar", "BC Place Vancouver"],
  ["2026-06-18", "A", "México", "Corea del Sur", "Estadio Guadalajara"],
  ["2026-06-19", "C", "Brasil", "Haití", "Philadelphia Stadium"],
  ["2026-06-19", "C", "Escocia", "Marruecos", "Boston Stadium"],
  ["2026-06-19", "D", "Turquía", "Paraguay", "San Francisco Bay Area Stadium"],
  ["2026-06-19", "D", "Estados Unidos", "Australia", "Seattle Stadium"],
  ["2026-06-20", "E", "Alemania", "Costa de Marfil", "Toronto Stadium"],
  ["2026-06-20", "E", "Ecuador", "Curazao", "Kansas City Stadium"],
  ["2026-06-20", "F", "Países Bajos", "Suecia", "Houston Stadium"],
  ["2026-06-20", "F", "Túnez", "Japón", "Estadio Monterrey"],
  ["2026-06-21", "H", "Uruguay", "Cabo Verde", "Miami Stadium"],
  ["2026-06-21", "H", "España", "Arabia Saudí", "Atlanta Stadium"],
  ["2026-06-21", "G", "Bélgica", "Irán", "Los Angeles Stadium"],
  ["2026-06-21", "G", "Nueva Zelanda", "Egipto", "BC Place Vancouver"],
  ["2026-06-22", "I", "Noruega", "Senegal", "New York New Jersey Stadium"],
  ["2026-06-22", "I", "Francia", "Irak", "Philadelphia Stadium"],
  ["2026-06-22", "J", "Argentina", "Austria", "Dallas Stadium"],
  ["2026-06-22", "J", "Jordania", "Argelia", "San Francisco Bay Area Stadium"],
  ["2026-06-23", "L", "Inglaterra", "Ghana", "Boston Stadium"],
  ["2026-06-23", "L", "Panamá", "Croacia", "Toronto Stadium"],
  ["2026-06-23", "K", "Portugal", "Uzbekistán", "Houston Stadium"],
  ["2026-06-23", "K", "Colombia", "RD Congo", "Estadio Guadalajara"],
  ["2026-06-24", "C", "Escocia", "Brasil", "Miami Stadium"],
  ["2026-06-24", "C", "Marruecos", "Haití", "Atlanta Stadium"],
  ["2026-06-24", "B", "Suiza", "Canadá", "BC Place Vancouver"],
  ["2026-06-24", "B", "Bosnia y Herzegovina", "Qatar", "Seattle Stadium"],
  ["2026-06-24", "A", "Chequia", "México", "Mexico City Stadium"],
  ["2026-06-24", "A", "Sudáfrica", "Corea del Sur", "Estadio Monterrey"],
  ["2026-06-25", "E", "Curazao", "Costa de Marfil", "Philadelphia Stadium"],
  ["2026-06-25", "E", "Ecuador", "Alemania", "New York New Jersey Stadium"],
  ["2026-06-25", "F", "Japón", "Suecia", "Dallas Stadium"],
  ["2026-06-25", "F", "Túnez", "Países Bajos", "Kansas City Stadium"],
  ["2026-06-25", "D", "Turquía", "Estados Unidos", "Los Angeles Stadium"],
  ["2026-06-25", "D", "Paraguay", "Australia", "San Francisco Bay Area Stadium"],
  ["2026-06-26", "I", "Noruega", "Francia", "Boston Stadium"],
  ["2026-06-26", "I", "Senegal", "Irak", "Toronto Stadium"],
  ["2026-06-26", "G", "Egipto", "Irán", "Seattle Stadium"],
  ["2026-06-26", "G", "Nueva Zelanda", "Bélgica", "BC Place Vancouver"],
  ["2026-06-26", "H", "Cabo Verde", "Arabia Saudí", "Houston Stadium"],
  ["2026-06-26", "H", "Uruguay", "España", "Estadio Guadalajara"],
  ["2026-06-27", "L", "Panamá", "Inglaterra", "New York New Jersey Stadium"],
  ["2026-06-27", "L", "Croacia", "Ghana", "Philadelphia Stadium"],
  ["2026-06-27", "J", "Argelia", "Austria", "Kansas City Stadium"],
  ["2026-06-27", "J", "Jordania", "Argentina", "Dallas Stadium"],
  ["2026-06-27", "K", "Colombia", "Portugal", "Miami Stadium"],
  ["2026-06-27", "K", "RD Congo", "Uzbekistán", "Atlanta Stadium"],
].map((match, index) => ({
  id: `m${String(index + 1).padStart(2, "0")}`,
  number: index + 1,
  date: match[0],
  group: match[1],
  home: match[2],
  away: match[3],
  venue: match[4],
}));
